//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panasonic_SmartClean
{
    using System;
    using System.Collections.Generic;
    
    public partial class CleanLog
    {
        public long LogIndex { get; set; }
        public Nullable<int> CabNo { get; set; }
        public string TaskIndex { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public Nullable<int> WorkPieceIndex { get; set; }
        public string Exist { get; set; }
        public string BarCode { get; set; }
        public string Ocr { get; set; }
        public string Type { get; set; }
        public string MouseResult { get; set; }
        public string ReflectPanelResult { get; set; }
        public string FlowResult { get; set; }
        public Nullable<int> FlowCount { get; set; }
        public string MouseBefore { get; set; }
        public string MouseAfter { get; set; }
        public string BoardBefore { get; set; }
        public string BoardAfter { get; set; }
        public string Operator { get; set; }
    }
}
